version: '3'

services:
    db:
        image: mariadb:latest
        environment:
            MYSQL_DATABASE: "${DATABASE_NAME}"
            MYSQL_USER: "${DATABASE_USER}"
            MYSQL_PASSWORD: "${DATABASE_PASSWORD}"
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        ports:
            - "3306:3306"
        volumes:
            - ./docker/.data/db:/var/lib/mysql
